
language: haskell

before_install: 
  - sudo apt-get install unixodbc-dev
  - git clone git://github.com/AmpersandTarski/ampersand-models.git ampersand-models

ghc: 7.8

after_script:
  - cat dist/test/*.log



